CREATE TABLE cats (
  cats_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  cats_name LONGTEXT NOT NULL,
  cats_breed TINYTEXT NOT NULL,
  cats_info LONGTEXT NOT NULL,
  cats_picture TINYTEXT NOT NULL
);
